# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-23 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellbill',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Store'),
            preserve_default=False,
        ),
    ]
